name: CI/CD
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: yarn install
      - run: yarn run test
  publish:
    name: Publish to expo
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: expo/expo-github-actions@v7
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: expo build:android -t apk